apps/backend/modules/user/controllers/UserController.php
<?php

namespace apps\backend\modules\user\controllers;

use Yii;
use common\modules\user\User;
use common\modules\user\UserSearch;
use apps\backend\controllers\BaseController;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * UserController implements the CRUD actions for User model.
 */
class UserController extends BaseController
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all User models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new UserSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single User model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new User model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new User();

        $model->setScenario('admin');
        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['index']);
            // return $this->redirect(['view', 'id' => $model->userId]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing User model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        $model->setScenario('admin');

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirectUpdateLastPage();
            // return $this->redirect(['view', 'id' => $model->userId]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing User model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the User model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return User the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = User::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

apps/backend/modules/user/controllers/UserSqcWithdrawController.php
<?php

namespace apps\backend\modules\user\controllers;

use common\modules\user\logic\UserSqcLogLogic;
use common\modules\user\map\UserSqcLogMap;
use common\modules\user\map\UserSqcWithdrawMap;
use common\modules\user\User;
use Yii;
use common\modules\user\UserSqcWithdraw;
use common\modules\user\search\UserSqcWithdrawSearch;
use apps\backend\controllers\BaseController;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * UserSqcWithdrawController implements the CRUD actions for UserSqcWithdraw model.
 */
class UserSqcWithdrawController extends BaseController
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    public function actionIndex()
    {
        $searchModel = new UserSqcWithdrawSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    public function actionCreate()
    {
        $model = new UserSqcWithdraw();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['index']);
            // return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }


    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
		$sqc = $model->totalMoney ?? 0;

        $db = $model::getDb()->beginTransaction();
        try {
			if (!empty($_POST)) {
				
				if (in_array($model->status, [UserSqcWithdrawMap::STATUS_FINISH, UserSqcWithdrawMap::STATUS_REJECT])) 
					throw new \Exception('不可再处理');
			}
            if ($model->load(Yii::$app->request->post()) && $model->save())  {
				$user = User::findOne($model->userId);
				// 拒绝
				if ($model->status == UserSqcWithdrawMap::STATUS_REJECT) {
	
					if ($sqc)
					    UserSqcLogLogic::increase($model->userId, $sqc, UserSqcLogMap::TYPE_WITHDRAW_RETURN, $this->userId);
				}
                $db->commit();
                return $this->redirectUpdateLastPage();
            }

            return $this->render('update', [
                'model' => $model,
            ]);
        } catch (\Exception $e) {
            $db->rollBack();
            throw $e;
        }
    }

    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the UserSqcWithdraw model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return UserSqcWithdraw the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = UserSqcWithdraw::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

apps/backend/modules/user/views/user-sqc-withdraw/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model common\modules\user\UserSqcWithdraw */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="user-sqc-withdraw-form">

    <?php $form = ActiveForm::begin([
    'options' => ['class' => 'form-horizontal'],
    'fieldConfig' => [
    'template' => '<label class="col-sm-2 control-label">{label}</label><div class="col-sm-5">{input}{error}{hint}</div>',
    ],
    ]); ?>
<div class="panel panel-primary">
    <div class="panel-heading">
             </div>
    <div class="panel-body">


    <?= $form->field($model, 'status')->dropDownList(\common\modules\user\map\UserSqcWithdrawMap::$status, ['value' => $model->status ?: \common\modules\user\map\UserSqcRechargeMap::STATUS_FINISH]) ?>

    <?= $form->field($model, 'reason')->textarea(['maxlength' => true, 'placeholder' => '如果拒绝，请填写拒绝原因']) ?>

    <?= $form->field($model, 'note')->textarea(['maxlength' => true, 'placeholder' => '仅管理员可见']) ?>

        <div class="form-group text-center">
            <?= Html::submitButton('提交', ['class' => 'btn btn-success']) ?>
        </div>
    </div>
</div>

    <?php ActiveForm::end(); ?>

</div>

apps/backend/modules/user/views/user-sqc-withdraw/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model common\modules\user\search\UserSqcWithdrawSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="user-sqc-withdraw-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?php  echo $form->field($model, 'status')->dropDownList(\common\modules\user\map\UserSqcWithdrawMap::$status, ['prompt' => '请选择']) ?>

    <?php // echo $form->field($model, 'address') ?>

    <?php // echo $form->field($model, 'name') ?>

    <?php // echo $form->field($model, 'createTime') ?>

    <?php // echo $form->field($model, 'handelTime') ?>

    <?php // echo $form->field($model, 'reason') ?>

    <?php // echo $form->field($model, 'note') ?>

    <div class="form-group">
        <?= Html::submitButton('搜索', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('重置', ['class' => 'btn btn-default']) ?>
        <div class="help-block"></div>
    </div>

    <?php ActiveForm::end(); ?>

</div>

apps/backend/modules/user/views/user-sqc-withdraw/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model common\modules\user\UserSqcWithdraw */

$this->title = '增加提现';
$this->params['breadcrumbs'][] = ['label' => '提现', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="user-sqc-withdraw-create">


    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

apps/backend/modules/user/views/user-sqc-withdraw/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel common\modules\user\search\UserSqcWithdrawSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = '提现';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="user-sqc-withdraw-index form-inline">

    <?php  echo $this->render('_search', ['model' => $searchModel]); ?>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        // 不显示搜索框 'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            'id',
            [
                'attribute' => 'userId',
                'format' => 'raw',
                'value' => function($data) {
                    return Html::a($data->user->nickname, ['user/view', 'id' => $data->user->userId]);
                }
            ],
            'totalMoney',
            'commission',
            'money',
            [
                'attribute' => 'status',
                'value' => function($data) {
                    return \common\modules\user\map\UserSqcWithdrawMap::$status[$data->status] ?? null;
                }
            ],
            'address',
//            'name',
            'createTime',
            'handelTime',
            'reason',
            'note',

            ['class' => 'yii\grid\ActionColumn', 'template' => '{update}'],
        ],
    ]); ?>
</div>

apps/backend/modules/user/views/user-sqc-withdraw/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model common\modules\user\UserSqcWithdraw */

$this->title = '修改';
$this->params['breadcrumbs'][] = ['label' => '提现', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->name, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = '修改';
?>
<div class="user-sqc-withdraw-update">

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

apps/backend/modules/user/views/user-sqc-withdraw/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model common\modules\user\UserSqcWithdraw */

$this->title = $model->name;
$this->params['breadcrumbs'][] = ['label' => '提现', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="user-sqc-withdraw-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => '确定删除吗？',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'userId',
            'totalMoney',
            'commission',
            'money',
            'status',
            'address',
            'name',
            'createTime',
            'handelTime',
            'reason',
            'note',
        ],
    ]) ?>

</div>